name: SMPRPG
version: ${project.version}
main: me.rey.smp.SMPRPG
api-version: 1.16
authors: [ Rey, Baloo ]
description: SMP for big brain buddies

commands:
  cigive:
    usage: /cigive <id>
    aliases: [customitemgive, customgive, ci, customitem]
